M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Thu 20 Mar 2025 11:06:58 AM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-20T11:06:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X75.97Y-95.972
X107.466Y-127.468
X138.962Y-95.972
T0
M30
